### ISSUE TITLE
really neccessary to require php 5.5 for this ? 

### ISSUE THREAD

**Issue by vesper8** [gabrielfs7/google-trends#1]
Nice library.. I planned on using it, but one of the servers I'd like to use it on is on Debian 6.. which doesn't have an easy-to-install version of php 5.5. I tried running composer update after adding your library and it said that it can't install because it requires php 5.5. Is this really neccessary?

**Comment by gabrielfs7** [comment]
Not necessarily PHP 5.5 is required, because I am not using "generators" or other php 5.5 features yet. Maybe I reduce for PHP 5.4 or later, but as I have only PHP 5.5 in my environment I established 5.5. I will change in composer.json to accept PHP 5.4 or later.

**Comment by gabrielfs7** [comment]
Since we already have php 7 available I will keep restriction to >= php 5.5.
