### ISSUE TITLE
Parse error: syntax error, unexpected '?' in google-trends-master/web/index.php on line 13

### ISSUE THREAD

**Issue by Sukhpall-Singh** [gabrielfs7/google-trends#12]
I am trying to integrate this on my site but I am facing above problem when i am implementing on server. I tested it on local system and its working fine but I dont know why it is not working on server. Here is the line in index.php where it is showing error:
 

>  $relatedSearchUrlBuilder = (new SearchFilter())
>         ->withCategory((int)($_GET['category'] ?? 0)) //All categories
> 
> 

Is there any php version problem? because in my local system I have installed php version 7.1.2 but on server its 5.6.2?
 Thanks!

**Comment by gabrielfs7** [comment]
@Sukhpall-Singh the error is because the package requires PHP 7.2+, but still works with 7.1 for some cases. In this case the Null Coalescing Operator (??) does not work on PHP5. 

I suggest you to upgrade, if possible, your production code to PHP7.2, since PHP5 does not receive support anymore.

**Comment by peterpeep** [comment]
Hi,
When I set the time to a few minutes or hours, it returns nothing. What's the issue? e.g:
    ->withinInterval(
            new DateTimeImmutable('now -1days'),
            new DateTimeImmutable('now')
        )

**Comment by gabrielfs7** [comment]
@peterpeep The search only works with yesterdays date as far as I know. I accept help if you manage to make it work with current time. I cannot check this issue for the moment.

**Comment by gabrielfs7** [comment]
Since there is now answers, I am closing this.
