### ISSUE TITLE
401 return

### ISSUE THREAD

**Issue by Vromain** [gabrielfs7/google-trends#14]
Hi,

When i try your exemple i got this Error
{"exception":"GSoares\\GoogleTrends\\Error\\GoogleTrendsException","error":"GoogleTrends error: Request error with status code \"401\" for url \"https:\/\/trends.google.com\/trends\/api\/widgetdata\/relatedsearches?hl=en-US&tz=-60&req=%7B%22restriction%22:%7B%22geo%22:%7B%22country%22:%22US%22%7D,%22time%22:%222020-07-06+2020-07-13%22,%22originalTimeRangeForExploreUrl%22:%222020-07-06+2020-07-13%22,%22complexKeywordsRestriction%22:%7B%22keyword%22:%5B%7B%22type%22:%22BROAD%22,%22value%22:%22google%22%7D%5D%7D%7D,%22keywordType%22:%22QUERY%22,%22metric%22:%5B%22TOP%22,%22RISING%22%5D,%22trendinessSettings%22:%7B%22compareTime%22:%222020-06-28+2020-07-05%22%7D,%22requestOptions%22:%7B%22property%22:%22%22,%22backend%22:%22IZG%22,%22category%22:0%7D,%22language%22:%22en%22%7D&token=APP6_UEAAAAAXw1-lpli501ENfcdBCX12-coE5gdXFRf\""}

My code

<?php

require __DIR__ . '/../vendor/autoload.php';

use GSoares\GoogleTrends\Search\InterestByRegionSearch;
use GSoares\GoogleTrends\Search\InterestOverTimeSearch;
use GSoares\GoogleTrends\Search\RelatedTopicsSearch;
use GSoares\GoogleTrends\Search\SearchFilter;
use GSoares\GoogleTrends\Search\RelatedQueriesSearch;
 
header('Content-Type', 'application/json');

try {
$searchFilter = (new GSoares\GoogleTrends\Search\SearchFilter())
        ->withCategory(0) //All categories
        ->withSearchTerm('google')
        ->withLocation('US')
        ->withinInterval(
            new DateTimeImmutable('now -7 days'),
            new DateTimeImmutable('now')
        )
        ->withLanguage('en-US')
        ->considerWebSearch()
        # ->considerImageSearch() // Consider only image search
        # ->considerNewsSearch() // Consider only news search
        # ->considerYoutubeSearch() // Consider only youtube search
        # ->considerGoogleShoppingSearch() // Consider only Google Shopping search
        ->withTopMetrics()
        ->withRisingMetrics();
        
$result = (new GSoares\GoogleTrends\Search\RelatedQueriesSearch())
    ->search($searchFilter)
    ->jsonSerialize();

    echo json_encode($result);
} catch (Throwable $exception) {
    echo json_encode(
        [
            'exception' => get_class($exception),
            'error' => $exception->getMessage()
        ]
    );
}

it's normal ?

**Comment by hemant17** [comment]
i got the same
`"{"exception":"GSoares\\GoogleTrends\\Error\\GoogleTrendsException","error":"GoogleTrends error: Request error with status code \"401\" for url \"https:\/\/trends.google.com\/trends\/api\/widgetdata\/relatedsearches?hl=en-US&tz=-60&req=%7B%22restriction%22:%7B%22geo%22:%7B%22country%22:%22US%22%7D,%22time%22:%222020-09-23+2020-09-30%22,%22originalTimeRangeForExploreUrl%22:%222020-09-23+2020-09-30%22,%22complexKeywordsRestriction%22:%7B%22keyword%22:%5B%7B%22type%22:%22BROAD%22,%22value%22:%22google%22%7D%5D%7D%7D,%22keywordType%22:%22QUERY%22,%22metric%22:%5B%22TOP%22,%22RISING%22%5D,%22trendinessSettings%22:%7B%22compareTime%22:%222020-09-15+2020-09-22%22%7D,%22requestOptions%22:%7B%22property%22:%22%22,%22backend%22:%22IZG%22,%22category%22:0%7D,%22language%22:%22en%22%7D&token=APP6_UEAAAAAX3YtVi-omFgJKF73i40AsXa2V9Z3ChyE\""} ◀"`

**Comment by gabrielfs7** [comment]
Sorry for the late response, but I did not have time to work on this before. :) 

Those issues were addressed here: https://github.com/gabrielfs7/google-trends/tree/2.0.0
