### ISSUE TITLE
401 unauthorize error

### ISSUE THREAD

**Issue by chistel** [gabrielfs7/google-trends#15]
Each time I set a location that's not US, I get 401 unauthorized error

**Comment by leobloise** [comment]
I'm going through it too

**Comment by tojoeugene** [comment]
The same error from my side also

**Comment by gabrielfs7** [comment]
This issue was fixed today in the version https://github.com/gabrielfs7/google-trends/tree/2.0.3

This was because the the userCountryCode must be US regardless the location. Please avoid also changing the language. Change only the location country.
