### ISSUE TITLE
Error 401 with Location and Language

### ISSUE THREAD

**Issue by IharenaTsiafoy** [gabrielfs7/google-trends#21]
Hello,
how to change countries and languages in API
Example: WithLocation(FR)
WithLanguage(en-FR)
Error 401

**Comment by gabrielfs7** [comment]
This issue was fixed today in the version https://github.com/gabrielfs7/google-trends/tree/2.0.3

This was because the the userCountryCode must be US regardless the location. Please avoid also changing the language. Change only the location country.
