### ISSUE TITLE
how to get IDs for other categories

### ISSUE THREAD

**Issue by vesper8** [gabrielfs7/google-trends#3]
I noticed in your category.php file you only set up the constant for BEAUTY_AND_FITNESS which is equal to '0-44'. I was wondering where you got that from and where can I get the codes for all the other categories?

**Comment by gabrielfs7** [comment]
This project is not stable yet, and I just wrote this category for initial tests. I take the category id exploring Google Trends website menu and source code of widgets. Will be awesome if you supply more categories for the project, cause is a open source project. Sorry my bad english.

**Comment by Jayaprakash20** [comment]
@vesper8  Im new to this opensource. May i know on what topic the discussions are going on?

**Comment by gabrielfs7** [comment]
Hello I have update the README.m file with link to get all categories. The project now has a stable version 1.0.0. 

Sorry for the huge delay on responding, but now I finally had time to work on this project.
