### ISSUE TITLE
quota reached after just 2 querries

### ISSUE THREAD

**Issue by vesper8** [gabrielfs7/google-trends#5]
I was testing this library and after running the same query just two times I reached the quota limit.

What is this limit? And why is it so small? I see other google-trends unofficial APIs use a username/password to get a bigger quota. Do you plan on adding this?

**Comment by gabrielfs7** [comment]
Yeah. you are right. I have to implement user authentication to improve the quota limit, feel free to collaborate with the project.
Thanks!

**Comment by gabrielfs7** [comment]
@vesper8 Now I have managed that situation by updating the cookie value on next request. Now google requires an special token for every kind of request.
