### ISSUE TITLE
This resource is no longer available...

### ISSUE THREAD

**Issue by sfatfarma** [gabrielfs7/google-trends#7]
Hello,

I think that the endpoint that this project uses, recently got shut down or moved. 

Check: 

https://trends.google.com/trends/fetchComponent?hl=en-US&cat=0-44&geo=US&q=hair&cid=TOP_QUERIES_0_0&date=today+1-m&cmpt=q&content=1&export=3

The response is: 

This resource is no longer available.
If you require support please email trends-data-request@google.com 
Please include details about how you are using the Trends data.

However, please correct me if I am wrong.

Regards,
Szabi.

**Comment by gabrielfs7** [comment]
Hello @sfatfarma. Yes, the endpoints were changed and I did not have time to update the project. Now everything is working. Sorry for the huge delay on responding.
